# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Large Social Surveys"                                
  description: "The LSS is a postgraduate and early career researcher led research group"  
  image: /img/my_image.jpg

  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "About Us"
        href: About Us/index.qmd
      - text: "Symposium"
        href: Symposium/index.qmd
    
    # your social media handles
    right:
      - icon: folder-symlink
        href: https://github.com/LargeSocialSurveys
      - icon: twitter
        href: https://twitter.com/LSocialSurveyRG
      - icon: envelope
        aria-label: email
        href: "mailto:mail.largesocialsurveys@gmail.com"  
  
  

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true